### PR TITLE
initial setup + seeding of data

### PR DESCRIPTION
**Pull request by gchzhen**
Initial setup includes:

Packages:

Webpack, Webpack CLI
Babel (loader, core, preset-react, preset-env)
Express
React, ReactDOM
MySQL

Other configs included:

Webpack config file,
barebones server config,
scripts to set/reset schema and seed data.

### CODE REVIEW

**Comment by gchzhen** [comment]
Thank you guys for your comments! @mchung1128 Date does not cause any errors, I've noticed this exact usage from TA. For loop creates a random number (between 1 to 20) of reviews for each listing. @matt-leyrat, could you elaborate on a new line character at the end of every file, please?

**Comment by matt-leyrat** [comment]
@gchzhen I'm not sure exactly what the reasoning is behind ending every file with a newline character, but after a quick search it seems like it has to do with file concatenation on Git's end.

**Comment by gchzhen** [comment]
@matt-leyrat great info, thanks! I'm working on a diff feature now and made sure that I ended every file with a new line character! I'm honestly not sure what must go to production dependencies, I thought that I followed instructions from docs and Webpack takes care of everything, but I for sure added dependencies which my client uses (like jquery) NOT in devDependencies, will fix everything as encounter errors and learn what must go to production as well, I guess! Feel free to teach me what must go to production if you're aware!

**Comment by matt-leyrat** [comment]
LGTM, merging!

**Pull request merged**
